@extends('layouts.app')
@section('title', config('store.name','TechZone').' — каталог электроники')
@section('meta_description', 'Каталог электроники с фильтрами, проверкой наличия и оформлением заказа онлайн.')
@section('content')
<section class="overflow-hidden bg-slate-950 text-white"><div class="mx-auto grid max-w-7xl gap-10 px-4 py-14 sm:px-6 sm:py-20 lg:grid-cols-[1.1fr_.9fr] lg:px-8">
<div class="max-w-2xl"><p class="inline-flex rounded-full border border-indigo-300/30 bg-indigo-400/10 px-3 py-1 text-xs font-semibold tracking-[.16em] text-indigo-200">ТЕХНИКА ДЛЯ ЖИЗНИ И РАБОТЫ</p><h1 class="mt-6 text-4xl font-semibold tracking-tight sm:text-5xl">Выбирайте технику спокойно.</h1><p class="mt-5 max-w-xl text-lg leading-8 text-slate-300">Понятный каталог, проверка наличия и подтверждение условий до оплаты.</p><div class="mt-8 flex flex-wrap gap-3"><a href="{{ route('products.index') }}" class="rounded-2xl bg-white px-5 py-3 text-sm font-semibold text-slate-950">Перейти в каталог</a>@if($saleProducts->isNotEmpty())<a href="{{ route('deals') }}" class="rounded-2xl border border-white/20 px-5 py-3 text-sm font-semibold">Товары со скидкой</a>@endif</div><dl class="mt-10 grid grid-cols-3 gap-4 border-t border-white/10 pt-6 text-sm"><div><dt class="text-slate-400">Товаров</dt><dd class="mt-1 text-lg font-semibold">{{ $productsCount }}</dd></div><div><dt class="text-slate-400">Поддержка</dt><dd class="mt-1 text-base font-semibold">{{ config('store.hours') ?: 'По графику' }}</dd></div><div><dt class="text-slate-400">Заказ</dt><dd class="mt-1 text-lg font-semibold">Онлайн</dd></div></dl></div>
@if($heroProduct)<a href="{{ route('products.show',$heroProduct->slug) }}" class="group relative min-h-72 overflow-hidden rounded-[2rem] border border-white/10 bg-gradient-to-br from-indigo-500/30 via-slate-900 to-cyan-400/20 p-6 shadow-2xl"><div class="absolute inset-0 bg-[radial-gradient(circle_at_70%_20%,rgba(255,255,255,.2),transparent_35%)]"></div><div class="relative grid h-full grid-rows-[minmax(0,1fr)_auto] gap-4"><div class="relative flex min-h-52 items-center justify-center overflow-hidden rounded-[1.5rem] bg-white/95 p-5 shadow-inner ring-1 ring-white/20"><div class="absolute inset-x-10 bottom-3 h-8 rounded-full bg-slate-900/10 blur-xl"></div><img src="{{ $heroProduct->main_image?->getUrl() ?? asset('images/product-placeholder.svg') }}" alt="{{ $heroProduct->name }}" class="relative mx-auto h-52 w-full object-contain transition duration-300 group-hover:scale-105"></div><div class="rounded-2xl bg-slate-950/70 p-4 backdrop-blur"><p class="text-sm text-slate-300">{{ $heroProduct->brand?->name }}</p><h2 class="mt-1 font-semibold">{{ $heroProduct->name }}</h2><p class="mt-2 text-lg font-semibold">{{ number_format($heroProduct->final_price,0,',',' ') }} ₽</p></div></div></a>@endif
</div></section>
<section class="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">@if($searchQuery!=='')<div class="mb-12"><div class="flex items-end justify-between gap-4"><div><p class="text-sm font-semibold text-indigo-600">РЕЗУЛЬТАТ ПОИСКА</p><h2 class="mt-1 text-2xl font-semibold">«{{ $searchQuery }}»</h2></div><a href="{{ route('products.index',['search'=>$searchQuery]) }}" class="text-sm font-semibold text-indigo-700">Все результаты →</a></div><div class="mt-6">@include('products.partials.cards',['products'=>$searchResults])</div>@if($searchResults->isEmpty())<p class="mt-5 rounded-2xl bg-slate-100 p-4 text-sm text-slate-600">Ничего не найдено.</p>@endif</div>@endif
<div class="flex items-end justify-between gap-4"><div><p class="text-sm font-semibold text-indigo-600">КАТАЛОГ</p><h2 class="mt-1 text-2xl font-semibold text-slate-950">Популярные категории</h2></div><a href="{{ route('products.index') }}" class="text-sm font-semibold text-indigo-700">Весь каталог →</a></div><div class="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@foreach($featuredCategories as $category)<a href="{{ route('products.index',['category'=>$category->id]) }}" class="group flex items-center justify-between rounded-2xl bg-white px-5 py-4 ring-1 ring-slate-200 hover:ring-indigo-300"><span><span class="block font-semibold group-hover:text-indigo-700">{{ $category->name }}</span><span class="mt-1 block text-sm text-slate-500">{{ $category->products_count }} товаров</span></span><span>→</span></a>@endforeach</div></section>
<section class="border-y border-slate-200 bg-white py-12"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="flex items-end justify-between"><div><p class="text-sm font-semibold text-indigo-600">ВЫБОР МАГАЗИНА</p><h2 class="mt-1 text-2xl font-semibold text-slate-950">Рекомендуемые товары</h2></div><a href="{{ route('products.index') }}" class="text-sm font-semibold text-indigo-700">Каталог →</a></div><div class="mt-6">@include('products.partials.cards',['products'=>$featuredProducts])</div></div></section>
<section class="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div class="flex items-end justify-between gap-4"><div><p class="text-sm font-semibold text-indigo-600">КАТАЛОГ</p><h2 class="mt-1 text-2xl font-semibold text-slate-950">Недавно обновлённые</h2></div><a href="{{ route('products.index') }}" class="text-sm font-semibold text-indigo-700">Все товары →</a></div><div class="mt-6">@include('products.partials.cards',['products'=>$recentProducts->take(4)])</div>@if($saleProducts->isNotEmpty())<div class="mt-12 border-t border-slate-200 pt-10"><div class="flex items-end justify-between gap-4"><div><p class="text-sm font-semibold text-rose-600">СНИЖЕННАЯ ЦЕНА</p><h2 class="mt-1 text-2xl font-semibold text-slate-950">Акции</h2></div><a href="{{ route('deals') }}" class="text-sm font-semibold text-indigo-700">Все акции →</a></div><div class="mt-6">@include('products.partials.cards',['products'=>$saleProducts->take(4)])</div></div>@endif</section>
<section class="border-t border-slate-200 bg-slate-100 py-12"><div class="mx-auto grid max-w-7xl gap-5 px-4 sm:grid-cols-3 sm:px-6 lg:px-8"><div class="rounded-2xl bg-white p-5"><h2 class="font-semibold">Проверка остатка</h2><p class="mt-2 text-sm leading-6 text-slate-600">При добавлении в корзину и перед созданием заказа.</p></div><div class="rounded-2xl bg-white p-5"><h2 class="font-semibold">Контроль цены</h2><p class="mt-2 text-sm leading-6 text-slate-600">Изменение цены показывается в корзине до оформления.</p></div><div class="rounded-2xl bg-white p-5"><h2 class="font-semibold">Условия до оплаты</h2><p class="mt-2 text-sm leading-6 text-slate-600">Доставка и способ оплаты подтверждаются заранее.</p></div></div></section>
@endsection
