@extends('layouts.app')
@section('title','Новый товар — управление')
@section('robots','noindex,nofollow')
@section('content')
<section class="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8">@include('admin.partials.nav')<a href="{{ route('admin.products.index') }}" class="text-sm font-semibold text-indigo-700">← Все товары</a><h1 class="mt-3 text-3xl font-semibold text-slate-950">Новый товар</h1><p class="mt-2 text-sm text-slate-500">После создания откроется расширенная форма характеристик и SEO.</p>
@if($errors->any())<div class="mt-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-800">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
<form action="{{ route('admin.products.store') }}" method="POST" enctype="multipart/form-data" class="mt-6 space-y-6">@csrf
<div class="rounded-3xl bg-white p-6 ring-1 ring-slate-200"><div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium">Название<input name="name" value="{{ old('name') }}" required class="mt-1.5 w-full rounded-xl border-slate-300"></label><label class="text-sm font-medium">Артикул<input name="sku" value="{{ old('sku') }}" required class="mt-1.5 w-full rounded-xl border-slate-300"></label><label class="text-sm font-medium">Модель<input name="model" value="{{ old('model') }}" class="mt-1.5 w-full rounded-xl border-slate-300"></label><label class="text-sm font-medium">Бренд<select name="brand_id" class="mt-1.5 w-full rounded-xl border-slate-300"><option value="">Без бренда</option>@foreach($brands as $brand)<option value="{{ $brand->id }}" @selected(old('brand_id')==$brand->id)>{{ $brand->name }}</option>@endforeach</select></label><label class="text-sm font-medium">Цена<input type="number" step="0.01" name="price" value="{{ old('price') }}" required class="mt-1.5 w-full rounded-xl border-slate-300"></label><label class="text-sm font-medium">Старая цена<input type="number" step="0.01" name="compare_price" value="{{ old('compare_price') }}" class="mt-1.5 w-full rounded-xl border-slate-300"></label><label class="text-sm font-medium">Остаток<input type="number" name="stock_quantity" value="{{ old('stock_quantity',0) }}" required class="mt-1.5 w-full rounded-xl border-slate-300"></label><label class="text-sm font-medium sm:col-span-2">Краткое описание<textarea name="short_description" rows="2" class="mt-1.5 w-full rounded-xl border-slate-300">{{ old('short_description') }}</textarea></label><label class="text-sm font-medium sm:col-span-2">Описание<textarea name="description" rows="5" class="mt-1.5 w-full rounded-xl border-slate-300">{{ old('description') }}</textarea></label></div><div class="mt-4 flex gap-5"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_active" value="1" checked>Сразу опубликовать</label><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_featured" value="1">Рекомендуемый</label></div></div>
<div class="rounded-3xl bg-white p-6 ring-1 ring-slate-200"><h2 class="font-semibold">Категории</h2><div class="mt-4 flex flex-wrap gap-3">@foreach($categories as $category)<label class="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm"><input type="checkbox" name="categories[]" value="{{ $category->id }}" @checked(in_array($category->id,old('categories',[])))>{{ $category->name }}</label>@endforeach</div></div>
<div class="rounded-3xl bg-white p-6 ring-1 ring-slate-200"><h2 class="font-semibold">Фотографии</h2><p class="mt-2 text-sm text-slate-500">Добавьте 1–5 фото. Первое станет главным. Все файлы будут приведены к WebP 1200×1200.</p><input type="file" name="images[]" multiple required accept="image/jpeg,image/png,image/webp,image/avif" class="mt-4 block w-full text-sm"></div>
<button class="rounded-xl bg-indigo-600 px-6 py-3 font-semibold text-white">Создать товар</button></form></section>
@endsection
