@extends('layouts.app')
@section('title','Редактирование '.$product->name)
@section('robots','noindex,nofollow')
@section('content')
<section class="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8">@include('admin.partials.nav')<a href="{{ route('admin.products.index') }}" class="text-sm font-semibold text-indigo-700">← Все товары</a><h1 class="mt-3 text-3xl font-semibold text-slate-950">{{ $product->name }}</h1>
@if($errors->any())<div class="mt-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-800">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
<form id="productForm" action="{{ route('admin.products.update',$product) }}" method="POST" enctype="multipart/form-data" class="mt-6 space-y-6">@csrf @method('PUT')
  <div class="rounded-3xl bg-white p-6 ring-1 ring-slate-200"><h2 class="text-lg font-semibold">Основные данные</h2><div class="mt-4 grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium">Название<input name="name" value="{{ old('name',$product->name) }}" required class="mt-1.5 w-full rounded-xl border-slate-300"></label><label class="text-sm font-medium">Артикул<input name="sku" value="{{ old('sku',$product->sku) }}" required class="mt-1.5 w-full rounded-xl border-slate-300"></label><label class="text-sm font-medium">Модель<input name="model" value="{{ old('model',$product->model) }}" class="mt-1.5 w-full rounded-xl border-slate-300"></label><label class="text-sm font-medium">Бренд<select name="brand_id" class="mt-1.5 w-full rounded-xl border-slate-300"><option value="">Без бренда</option>@foreach($brands as $brand)<option value="{{ $brand->id }}" @selected(old('brand_id',$product->brand_id)==$brand->id)>{{ $brand->name }}</option>@endforeach</select></label><label class="text-sm font-medium sm:col-span-2">Краткое описание<textarea name="short_description" rows="2" class="mt-1.5 w-full rounded-xl border-slate-300">{{ old('short_description',$product->short_description) }}</textarea></label><label class="text-sm font-medium sm:col-span-2">Полное описание<textarea name="description" rows="6" class="mt-1.5 w-full rounded-xl border-slate-300">{{ old('description',$product->description) }}</textarea></label></div></div>
  <div class="grid gap-6 lg:grid-cols-2"><div class="rounded-3xl bg-white p-6 ring-1 ring-slate-200"><h2 class="text-lg font-semibold">Цена и остаток</h2><div class="mt-4 grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium">Цена<input type="number" step="0.01" name="price" value="{{ old('price',$product->price) }}" required class="mt-1.5 w-full rounded-xl border-slate-300"></label><label class="text-sm font-medium">Старая цена<input type="number" step="0.01" name="compare_price" value="{{ old('compare_price',$product->compare_price) }}" class="mt-1.5 w-full rounded-xl border-slate-300"></label><label class="text-sm font-medium">Себестоимость<input type="number" step="0.01" name="cost" value="{{ old('cost',$product->cost) }}" class="mt-1.5 w-full rounded-xl border-slate-300"></label><label class="text-sm font-medium">Остаток<input type="number" name="stock_quantity" value="{{ old('stock_quantity',$product->stock?->quantity ?? 0) }}" required class="mt-1.5 w-full rounded-xl border-slate-300"></label><label class="text-sm font-medium">Цена проверена<input type="datetime-local" name="price_verified_at" value="{{ old('price_verified_at',$product->price_verified_at?->format('Y-m-d\TH:i')) }}" class="mt-1.5 w-full rounded-xl border-slate-300"></label></div><div class="mt-4 flex gap-5"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$product->is_active))>Активен</label><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured',$product->is_featured))>Рекомендуемый</label></div></div>
  <div class="rounded-3xl bg-white p-6 ring-1 ring-slate-200"><h2 class="text-lg font-semibold">Характеристики</h2><div class="mt-4 grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium">Страна<input name="country_of_origin" value="{{ old('country_of_origin',$product->country_of_origin) }}" class="mt-1.5 w-full rounded-xl border-slate-300"></label><label class="text-sm font-medium">Гарантия, мес.<input type="number" name="warranty_months" value="{{ old('warranty_months',$product->warranty_months) }}" class="mt-1.5 w-full rounded-xl border-slate-300"></label><label class="text-sm font-medium">Вес<input type="number" step="0.01" name="weight" value="{{ old('weight',$product->weight) }}" class="mt-1.5 w-full rounded-xl border-slate-300"></label><label class="text-sm font-medium">Размеры<input name="dimensions" value="{{ old('dimensions',$product->dimensions) }}" class="mt-1.5 w-full rounded-xl border-slate-300"></label><label class="text-sm font-medium sm:col-span-2">Комплектация<textarea name="package_contents" rows="3" class="mt-1.5 w-full rounded-xl border-slate-300">{{ old('package_contents',$product->package_contents) }}</textarea></label></div></div></div>
  <div class="rounded-3xl bg-white p-6 ring-1 ring-slate-200"><h2 class="text-lg font-semibold">Категории</h2><div class="mt-4 flex flex-wrap gap-3">@foreach($categories as $category)<label class="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm"><input type="checkbox" name="categories[]" value="{{ $category->id }}" @checked(in_array($category->id,old('categories',$product->categories->pluck('id')->all())))>{{ $category->name }}</label>@endforeach</div></div>
  <div class="rounded-3xl bg-white p-6 ring-1 ring-slate-200"><h2 class="text-lg font-semibold">SEO</h2><div class="mt-4 grid gap-4"><label class="text-sm font-medium">SEO-заголовок<input name="meta_title" value="{{ old('meta_title',$product->meta_title) }}" class="mt-1.5 w-full rounded-xl border-slate-300"></label><label class="text-sm font-medium">SEO-описание<textarea name="meta_description" rows="2" class="mt-1.5 w-full rounded-xl border-slate-300">{{ old('meta_description',$product->meta_description) }}</textarea></label></div></div>
  <div class="rounded-3xl bg-white p-6 ring-1 ring-slate-200"><h2 class="text-lg font-semibold">Добавить фотографии</h2><p class="mt-2 text-sm text-slate-500">До 5 файлов. При загрузке они автоматически преобразуются в WebP 1200×1200 на белом фоне.</p><input type="file" name="images[]" multiple accept="image/jpeg,image/png,image/webp,image/avif" class="mt-4 block w-full text-sm"></div>
  <button class="rounded-xl bg-indigo-600 px-6 py-3 font-semibold text-white">Сохранить товар</button>
</form>
@if($product->images->isNotEmpty())<div class="mt-6 rounded-3xl bg-white p-6 ring-1 ring-slate-200"><h2 class="text-lg font-semibold">Фотографии</h2><div class="mt-4 grid gap-4 sm:grid-cols-3 lg:grid-cols-4">@foreach($product->images as $image)<div class="rounded-2xl border border-slate-200 p-3"><img src="{{ $image->getUrl() }}" class="aspect-square w-full rounded-xl bg-slate-50 object-contain" alt=""><label class="mt-3 flex items-center gap-2 text-sm"><input form="productForm" type="radio" name="main_image_id" value="{{ $image->id }}" @checked($image->is_main)>Главное фото</label><form action="{{ route('admin.products.images.destroy',[$product,$image]) }}" method="POST" class="mt-2" onsubmit="return confirm('Удалить фотографию?')">@csrf @method('DELETE')<button class="text-sm font-semibold text-rose-700">Удалить</button></form></div>@endforeach</div><p class="mt-3 text-xs text-slate-500">После выбора главного фото нажмите «Сохранить товар» выше.</p></div>@endif
</section>
@endsection
