@extends('layouts.app')
@section('title', 'Оформление заказа — '.config('store.name', 'TechZone'))
@section('robots', 'noindex,nofollow')
@section('content')
<section class="py-10"><div class="mx-auto grid max-w-6xl gap-6 px-4 sm:px-6 lg:grid-cols-[1fr_360px] lg:px-8">
<form action="{{ route('checkout.store') }}" method="POST" class="rounded-3xl bg-white p-6 ring-1 ring-slate-200" data-checkout-form>@csrf<h1 class="text-2xl font-semibold text-slate-950">Оформление заказа</h1><p class="mt-2 text-sm leading-6 text-slate-600">Наличие уже проверяется системой. Менеджер уточнит доставку и подтвердит итоговую сумму до оплаты.</p>
@if($errors->any())<div class="mt-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-800">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
<div class="mt-6 grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium">Имя<input name="name" value="{{ old('name',auth()->user()?->name) }}" required autocomplete="name" class="mt-1.5 w-full rounded-xl border-slate-300"></label><label class="text-sm font-medium">Телефон<input name="phone" value="{{ old('phone',auth()->user()?->phone) }}" required autocomplete="tel" class="mt-1.5 w-full rounded-xl border-slate-300"></label><label class="text-sm font-medium sm:col-span-2">Email <span class="font-normal text-slate-500">(для подтверждения)</span><input type="email" name="email" value="{{ old('email',auth()->user()?->email) }}" class="mt-1.5 w-full rounded-xl border-slate-300"></label><label class="text-sm font-medium sm:col-span-2">Город и адрес доставки<textarea name="shipping_address" rows="3" required class="mt-1.5 w-full rounded-xl border-slate-300">{{ old('shipping_address',auth()->user()?->address) }}</textarea></label></div>
<fieldset class="mt-6"><legend class="text-sm font-medium">Оплата</legend><div class="mt-2 grid gap-3 sm:grid-cols-2"><label class="flex gap-3 rounded-2xl border border-slate-200 p-4"><input type="radio" name="payment_method" value="card_on_delivery" @checked(old('payment_method','card_on_delivery')==='card_on_delivery')><span><span class="block text-sm font-semibold">При получении</span><span class="text-xs text-slate-500">Если доступно для выбранной доставки.</span></span></label><label class="flex gap-3 rounded-2xl border border-slate-200 p-4"><input type="radio" name="payment_method" value="bank_transfer" @checked(old('payment_method')==='bank_transfer')><span><span class="block text-sm font-semibold">По счёту</span><span class="text-xs text-slate-500">Для юридических лиц и ИП.</span></span></label></div></fieldset>
<label class="mt-5 block text-sm font-medium">Комментарий<textarea name="customer_note" rows="3" class="mt-1.5 w-full rounded-xl border-slate-300">{{ old('customer_note') }}</textarea></label>
<label class="mt-5 flex items-start gap-3 text-sm text-slate-600"><input type="checkbox" name="privacy_consent" value="1" required class="mt-1 rounded border-slate-300 text-indigo-600"><span>Согласен на обработку данных по <a href="{{ route('privacy') }}" class="font-semibold text-indigo-700">политике конфиденциальности</a>.</span></label><label class="mt-3 flex items-start gap-3 text-sm text-slate-600"><input type="checkbox" name="terms_consent" value="1" required class="mt-1 rounded border-slate-300 text-indigo-600"><span>Принимаю <a href="{{ route('terms') }}" class="font-semibold text-indigo-700">условия оформления заказа</a>.</span></label>
<button type="submit" data-checkout-button class="mt-6 w-full rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white disabled:opacity-60">Создать заказ</button></form>
<aside class="h-fit rounded-3xl bg-white p-6 ring-1 ring-slate-200"><h2 class="text-lg font-semibold">Ваш заказ</h2><ul class="mt-4 divide-y divide-slate-100">@foreach($items as $item)<li class="py-3"><div class="flex justify-between gap-4 text-sm"><span class="font-medium">{{ $item->product->name }}</span><span class="whitespace-nowrap font-semibold">{{ number_format($item->price*$item->quantity,0,',',' ') }} ₽</span></div><p class="mt-1 text-xs text-slate-500">{{ $item->quantity }} шт.@if($item->variant_attributes) · {{ $item->variant_attributes }}@endif</p></li>@endforeach</ul><dl class="mt-4 space-y-2 border-t pt-4 text-sm"><div class="flex justify-between"><dt>Товары</dt><dd>{{ number_format($subtotal,0,',',' ') }} ₽</dd></div>@if($discount>0)<div class="flex justify-between text-emerald-700"><dt>Скидка</dt><dd>−{{ number_format($discount,0,',',' ') }} ₽</dd></div>@endif<div class="flex justify-between text-lg font-semibold"><dt>Без доставки</dt><dd>{{ number_format($total,0,',',' ') }} ₽</dd></div></dl><p class="mt-4 text-xs leading-5 text-slate-500">{{ config('store.delivery_note') }}</p><a href="{{ route('cart.index') }}" class="mt-4 block text-center text-sm font-semibold text-indigo-700">Вернуться в корзину</a></aside>
</div></section>
@push('scripts')<script>document.querySelector('[data-checkout-form]')?.addEventListener('submit',()=>{const button=document.querySelector('[data-checkout-button]');if(button){button.disabled=true;button.textContent='Создаём заказ…';}});</script>@endpush
@endsection
