@extends('layouts.app')
@section('title', 'Заказ '.$order->order_number.' — '.config('store.name', 'TechZone'))
@section('robots', 'noindex,nofollow')
@section('content')
<section class="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8"><a href="{{ route('orders.index') }}" class="text-sm font-semibold text-indigo-700">← Все заказы</a><div class="mt-4 flex flex-wrap items-end justify-between gap-4"><div><h1 class="text-3xl font-semibold text-slate-950">{{ $order->order_number }}</h1><p class="mt-2 text-sm text-slate-500">{{ $order->created_at->format('d.m.Y H:i') }}</p></div><span class="rounded-full bg-indigo-50 px-3 py-1 text-sm font-semibold text-indigo-700">{{ $order->status_label }}</span></div>
  <div class="mt-8 grid gap-6 lg:grid-cols-[1fr_320px]"><div class="rounded-3xl bg-white p-6 ring-1 ring-slate-200"><h2 class="text-lg font-semibold">Состав заказа</h2><ul class="mt-4 divide-y divide-slate-100">@foreach($order->items as $item)<li class="flex justify-between gap-4 py-4"><div><p class="font-medium">{{ $item->product_name }}</p>@if($item->variant_attributes)<p class="text-sm text-slate-500">{{ $item->variant_attributes }}</p>@endif<p class="text-sm text-slate-500">{{ $item->quantity }} × {{ number_format($item->price,0,',',' ') }} ₽</p></div><p class="font-semibold">{{ number_format($item->total,0,',',' ') }} ₽</p></li>@endforeach</ul></div><aside class="h-fit rounded-3xl bg-white p-6 ring-1 ring-slate-200"><dl class="space-y-3 text-sm"><div class="flex justify-between"><dt class="text-slate-500">Товары</dt><dd>{{ number_format($order->subtotal,0,',',' ') }} ₽</dd></div>@if($order->discount_amount>0)<div class="flex justify-between text-emerald-700"><dt>Скидка</dt><dd>−{{ number_format($order->discount_amount,0,',',' ') }} ₽</dd></div>@endif<div class="flex justify-between border-t pt-3 text-base font-semibold"><dt>Итого без доставки</dt><dd>{{ number_format($order->total,0,',',' ') }} ₽</dd></div></dl><p class="mt-4 text-xs leading-5 text-slate-500">Стоимость доставки согласуется до оплаты.</p><p class="mt-4 text-sm text-slate-600">{{ $order->shipping_address }}</p></aside></div>
  @if($order->histories->isNotEmpty())<div class="mt-6 rounded-3xl bg-white p-6 ring-1 ring-slate-200"><h2 class="font-semibold">История статусов</h2><ol class="mt-4 space-y-3">@foreach($order->histories as $history)<li class="text-sm"><span class="font-medium">{{ $history->created_at->format('d.m.Y H:i') }}</span> · {{ $history->status }}@if($history->note)<span class="text-slate-500"> — {{ $history->note }}</span>@endif</li>@endforeach</ol></div>@endif
</section>
@endsection
